### ISSUE TITLE
Nem-funkcionális jellemzők vizsgálata

### ISSUE THREAD

**Issue by BACHlazs** [BME-MIT-IET/iet-hf2021-create-a-new-team#1]

**Comment by scrappy9** [comment]
Először a könyvtár memóriahasználatának hatékonyságát vizsgálom meg. Ez fontos tulajdonság mert erősen befolyásolja a memóriában tárolható hármasok számát és így a gráfok maximális méretét adott memórialimit mellett.

**Comment by scrappy9** [comment]
A tesztek elvégzéséhez a https://www.dbpedia.org/resources/ oldalon találhatóak megfelelő méretű adathalmazok. Az RDF gyakorlatokon használt fájlt is érdemes lehet használnom, mivel már részben ismerem a struktúráját: https://edu.vik.bme.hu/pluginfile.php/205572/mod_resource/content/1/szepmuveszeti.n3
