### ISSUE TITLE
Build keretrendszer és CI beüzemelése

### ISSUE THREAD

**Issue by BACHlazs** [BME-MIT-IET/iet-hf2021-create-a-new-team#2]

**Comment by SzTamas98** [comment]
Egy alap build és CI felrakva (buildel minden push/pull request-nél minden branchen és a mainen is), csak a mainen tudok kényelmesen commitolni (illetve mindig új branchet kéne létrehoznom), úgyhogy a branchemet annyira nem tudom kihasználni.

**Comment by BACHlazs** [comment]
Beüzemelt CI-t és módosításait átnéztem, minden OK!
